# Generated by Django 5.0.1 on 2024-01-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='saloon',
        ),
    ]
