# Generated by Django 4.2.7 on 2024-01-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0002_rename_book_saloon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='saloon',
        ),
    ]
